apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: o5gs-up
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: open5gs
  install:
    createNamespace: true  
  chart:
    spec:
      chart: o5gs-user-plane
      version: '0.0.1'
      sourceRef:
        kind: HelmRepository
        name: o5gs
  releaseName: o5gs-up
  values:
    multus:
      macVlanInterface: ens19
